Disproof of Concept
ClientView does not receive event (for reasons)
User ApplicationContext (instead of EventBus) for publishing results in:

org.springframework.beans.factory.support.ScopeNotActiveException: Error creating bean with name 'viewCache': Scope 'vaadin-ui' is not active for the current thread; consider defining a scoped proxy for this bean if you intend to refer to it from a singleton; nested exception is java.lang.IllegalStateException: No VaadinSession bound to current thread